name: flutter_application_2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0 # 안정적인 이전 버전
  shared_preferences: ^2.0.0
  ed_screen_recorder: ^0.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
    - assets/profile.webp
    - assets/intj.txt
