server : 
  port : 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force : true


spring:
  application:
    name: solstory # 어플리케이션 이름

  # DB:oracle 계정
  datasource: 
    url: jdbc:oracle:thin:@//localhost:1521/xe?ssl=false
    username: solstory
    password: eyessolstory
    driver-class-name: oracle.jdbc.OracleDriver
  
  # JPA
  jpa:
    hibernate:
      ddl-auto: update # create, update, none - 애플리케이션 가동시 스키마 관리 타입
    show-sql: true # sql문 출력
    properties:
      hibernate:
        "[format:sql]": true

# 로깅 수준 지정
logging:
  level:
    "[org.hibernate.SQL]": debug
    "[org.hibernate.orm.jdbc.bind]": trace
    "[org.springframework.web.socket]": trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    
api:
  key: 'cb6cca464d504a29a809ced072ba5aec'