server : 
  port : 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true


spring:
  application:
    name: solstory # 어플리케이션 이름

  # DB:oracle 계정
  datasource: 
    url: jdbc:oracle:thin:@//localhost:1521/xe?ssl=false
    username: solstory
    password: eyessolstory
    driver-class-name: oracle.jdbc.OracleDriver
  
  # JPA
  jpa:
    hibernate:
      ddl-auto: update # create, update, none - 애플리케이션 가동시 스키마 관리 타입
    show-sql: true # sql문 출력
    properties:
      hibernate:
        "[format:sql]": false

## 아래 설정 사용할 때 까지 해제
# mybatis : 
  #  mapper-locations: classpath:mapper/*.xml

# 로깅 수준 지정
# logging:
#  level:
#    "[org.hibernate.SQL]": debug
#    "[org.hibernate.orm.jdbc.bind]": trace
#    "[org.springframework.web.socket]": trace

api:
  key: API-KEY