server : 
  port : 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true


spring:
  application:
    name: solstory # 어플리케이션 이름

  # DB:oracle 계정
  datasource: 
    url: jdbc:oracle:thin:@//localhost:1521/xe?ssl=false
    username: solstroy
    password: eyessolstory
    driver-class-name: oracle.jdbc.OracleDriver
  
  # JPA
  jpa:
    hibernate:
      ddl-auto: create # create, update, none - 애플리케이션 가동시 스키마 관리 타입
    show-sql: true ##sql문 출력
    properties:
      hibernate:
        "[format:sql]": true

# 로깅 수준 지정
logging:
  level:
    "[org.hibernate.SQL]": debug
    "[org.hibernate.orm.jdbc.bind]": trace
    "[org.springframework.web.socket]": trace
  file:
    name:
      logs/solstory.log